name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-lock.yaml'

    - name: Install pnpm
      run: npm install -g pnpm  # 安装 pnpm

    - name: Install dependencies
      run: pnpm install  # 执行 pnpm i 安装依赖

    - name: Run build
      run: pnpm run build --if-present  # 如果有 build 脚本则执行

    - name: Start project
      run: node .  # 启动项目
